
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS student;
CREATE TABLE student (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    name VARCHAR (32),
    password VARCHAR (32)
    );

DROP TABLE IF EXISTS Category;
CREATE TABLE Category (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    name VARCHAR (32),
    parent_id INTEGER
    );
	
COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
